name: Prospecting for Gold
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8017654032446444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#099455'
    - '#0f6d3d'
    - '#09542b'
    - '#48612a'
    - '#28ab71'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
